// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervasyonSistemi.API.Data;

#nullable disable

namespace RezervasyonSistemi.API.Migrations
{
    [DbContext(typeof(RezervasyonDbContext))]
    [Migration("20260806103114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Alan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("KatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KatId", "Ad")
                        .IsUnique();

                    b.ToTable("Alanlar");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Bina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TesisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TesisId", "Ad")
                        .IsUnique();

                    b.ToTable("Binalar");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Kat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("BinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BinaId", "Ad")
                        .IsUnique();

                    b.ToTable("Katlar");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Rezervasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlanId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Tesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Tesisler");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Alan", b =>
                {
                    b.HasOne("RezervasyonSistemi.API.Models.Kat", "Kat")
                        .WithMany("Alanlar")
                        .HasForeignKey("KatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kat");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Bina", b =>
                {
                    b.HasOne("RezervasyonSistemi.API.Models.Tesis", "Tesis")
                        .WithMany("Binalar")
                        .HasForeignKey("TesisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tesis");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Kat", b =>
                {
                    b.HasOne("RezervasyonSistemi.API.Models.Bina", "Bina")
                        .WithMany("Katlar")
                        .HasForeignKey("BinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bina");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Rezervasyon", b =>
                {
                    b.HasOne("RezervasyonSistemi.API.Models.Alan", "Alan")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("AlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RezervasyonSistemi.API.Models.Kullanici", "Kullanici")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alan");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Alan", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Bina", b =>
                {
                    b.Navigation("Katlar");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Kat", b =>
                {
                    b.Navigation("Alanlar");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Kullanici", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("RezervasyonSistemi.API.Models.Tesis", b =>
                {
                    b.Navigation("Binalar");
                });
#pragma warning restore 612, 618
        }
    }
}
